# This file contains constants and config values for the asteroids game

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

FRAMES_PER_SECOND = 60

PLAYER_RADIUS = 20
PLAYER_COLOR = (255, 255, 255)

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS